name: DockerHub
run-name: Create, Test and Push Docker image to DockerHub

on:
  push:
    branches: [ "docker" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/pull_request_dev.yml'
    tags:
      - 'v*'
  pull_request:
    branches: [ "docker" ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/pull_request_dev.yml'

#env:
#  # github.repository as <account>/<repo>
#  IMAGE_NAME: ${{ github.repository }}


jobs:
  create_docker_image:
    name: Create Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        #if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: plitkarka/back_dev
          tags: |
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            # custom label
            type=raw,value=dev-{{sha}},enable=${{ github.ref == format('refs/heads/{0}', 'docker') }}
            

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true #${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
